// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialLink.Messaging.Data;

#nullable disable

namespace SocialLink.Messaging.Migrations
{
    [DbContext(typeof(EFMessagingDatabaseContext))]
    partial class EFMessagingDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("messaging")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SocialLink.Messaging.Domain.Relational.ChatGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastChangedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastChangedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastMessageOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastMessagePreview")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ChatGroup", "messaging");
                });

            modelBuilder.Entity("SocialLink.Messaging.Domain.Relational.ChatGroupUser", b =>
                {
                    b.Property<Guid>("ChatGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastChangedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastReadMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ChatGroupId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatGroupUser", "messaging");
                });

            modelBuilder.Entity("SocialLink.Messaging.Domain.Relational.ChatGroupUser", b =>
                {
                    b.HasOne("SocialLink.Messaging.Domain.Relational.ChatGroup", "ChatGroup")
                        .WithMany("Users")
                        .HasForeignKey("ChatGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChatGroup");
                });

            modelBuilder.Entity("SocialLink.Messaging.Domain.Relational.ChatGroup", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
