@SocialMedia.Web_HostAddress = https://localhost:7175/blobs
@SocialMedia.AccessToken = 123
@SocialMedia.BlobId = 1

POST {{SocialMedia.Web_HostAddress}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{SocialMedia.AccessToken}}

{
    "BlobIds": "[]"
}

###

GET {{SocialMedia.Web_HostAddress}}/{{SocialMedia.BlobId}}
Accept: application/json
Authorization: Bearer {{SocialMedia.AccessToken}}

###

POST {{SocialMedia.Web_HostAddress}}/delete
Content-Type: application/json
Authorization: Bearer {{SocialMedia.AccessToken}}

{
    "BlobId": "{{SocialMedia.BlobId}}
}

###

POST {{SocialMedia.Web_HostAddress}}/restore
Content-Type: application/json
Authorization: Bearer {{SocialMedia.AccessToken}}

{
    "BlobId": "{{SocialMedia.BlobId}}
}