@SocialMedia.Web_HostAddress = https://localhost:7175/notifications
@SocialMedia.AccessToken = 123
@SocialMedia.UserId = 00000000-0000-0000-0000-000000000001

POST {{SocialMedia.Web_HostAddress}}
Accept: application/json
Content-Type: application/json
Authorize: Bearer {{SocialMedia.AccessToken}}

{
    "UserId": "{{SocialMedia.UserId}}"
}

###

POST {{SocialMedia.Web_HostAddress}}/read
Accept: application/json
Authorize: Bearer {{SocialMedia.AccessToken}}

{}