@SocialMedia.Web_HostAddress = https://localhost:7175/posts
@SocialMedia.AccessToken = 123
@SocialMedia.PostId = 00000000-0000-0000-0000-000000000001

GET {{SocialMedia.Web_HostAddress}}/{{SocialMedia.PostId}}
Accept: application/json
Authorization: Bearer {{SocialMedia.AccessToken}}

###

POST {{SocialMedia.Web_HostAddress}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{SocialMedia.AccessToken}}

{
    "UserId": ""
}

###

POST {{SocialMedia.Web_HostAddress}}/comments
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{SocialMedia.AccessToken}}

{
    "PostId": {{SocialMedia.PostId}}
}

###

POST {{SocialMedia.Web_HostAddress}}/comments/create
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{SocialMedia.AccessToken}}

{
    "UserId": "",
    "PostId": {{SocialMedia.PostId}},
    "ParentId: "null",
    "Message": ""
}

###

POST {{SocialMedia.Web_HostAddress}}/comments/update
Content-Type: application/json
Authorization: Bearer {{SocialMedia.AccessToken}}

{
    "Id": "",
    "UserId": "",
    "PostId": {{SocialMedia.PostId}},
    "ParentId: "null",
    "Message": ""
}

###