@SocialMedia.Web_HostAddress = https://localhost:7175/users
@SocialMedia.AccessToken = 123

POST {{SocialMedia.Web_HostAddress}}/login
Accept: application/json
Content-Type: application/json

{
    "email": "b",
    "password": "123"
}

###

GET {{SocialMedia.Web_HostAddress}}/profile/00000000-0000-0000-0000-000000000001
Accept: application/json
Authorization: Bearer {{SocialMedia.AccessToken}}

###

POST {{SocialMedia.Web_HostAddress}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{SocialMedia.AccessToken}}

{}

###