@SocialMedia.Web_HostAddress = https://localhost:7175/users
@SocialMedia.AccessToken = 123
@SocialMedia.UserId = 00000000-0000-0000-0000-000000000001

POST {{SocialMedia.Web_HostAddress}}/login
Accept: application/json
Content-Type: application/json

{
    "email": "",
    "password": ""
}

###

GET {{SocialMedia.Web_HostAddress}}/profile/{{SocialMedia.UserId}}
Accept: application/json
Authorization: Bearer {{SocialMedia.AccessToken}}

###

POST {{SocialMedia.Web_HostAddress}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{SocialMedia.AccessToken}}

{}

###

POST {{SocialMedia.Web_HostAddress}}/update
Accept: application/json
Authorization: Bearer {{SocialMedia.AccessToken}}

{}

###

POST {{SocialMedia.Web_HostAddress}}/follow
Accept: application/json
Authorization: Bearer {{SocialMedia.AccessToken}}

{
    "FollowerId": "",
    "FollowingId": ""
}

###

POST {{SocialMedia.Web_HostAddress}}/unfollow
Accept: application/json
Authorization: Bearer {{SocialMedia.AccessToken}}

{
    "FollowerId": "",
    "FollowingId": ""
}

###

POST {{SocialMedia.Web_HostAddress}}/checkFollowStatus
Accept: application/json
Authorization: Bearer {{SocialMedia.AccessToken}}

{
    "FollowerId": "",
    "FollowingId": ""
}

###

POST {{SocialMedia.Web_HostAddress}}/acceptFollow
Accept: application/json
Authorization: Bearer {{SocialMedia.AccessToken}}

{
    "FollowerId": "",
    "FollowingId": ""
}

###

POST {{SocialMedia.Web_HostAddress}}/rejectFollow
Accept: application/json
Authorization: Bearer {{SocialMedia.AccessToken}}

{
    "FollowerId": "",
    "FollowingId": ""
}

###

GET {{SocialMedia.Web_HostAddress}}/notificationPreferences/{{SocialMedia.UserId}}
Accept: application/json
Authorization: Bearer {{SocialMedia.AccessToken}}

###

POST {{SocialMedia.Web_HostAddress}}/saveNotificationPreferences
Accept: application/json
Authorization: Bearer {{SocialMedia.AccessToken}}

{
    "Preferences": "[]"
}
